__asm__(
".set push\n"
".set noreorder\n"
".text \n"
".global _" START "\n"
".global " START "\n"
".type   _" START ", @function\n"
".type   " START ", @function\n"
"_" START ":\n"
"" START ":\n"
"	move $fp, $zero \n"
"	lapc $t9, " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
"	lapc $a1, _DYNAMIC \n"
"	lapc[48] $gp, _gp \n"
"	move $a0, $sp \n"
"	and $sp, $sp, -16 \n"
"	jalrc $t9 \n"
".set pop \n"
);
