__asm__(
".set push\n"
".set noreorder\n"
".text \n"
".global _" START "\n"
".global " START "\n"
".type   _" START ", @function\n"
".type   " START ", @function\n"
"_" START ":\n"
"" START ":\n"
"	move $fp, $0 \n"
"	.align 2 \n"
"	balc32 1f \n"
"	.gpword . \n"
"	.gpword " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
"	.gpword _DYNAMIC \n"
"1:	lw $t0, 0($ra) \n"
"	subu $t0, $ra, $t0 \n"
"	move $4, $sp \n"
"	lw $5, 8($ra) \n"
"	addu $5, $5, $t0 \n"
"	lw $25, 4($ra) \n"
"	addu $25, $25, $t0 \n"
"	and $sp, $sp, -16 \n"
"	subu $sp, $sp, 16 \n"
"	la $gp, _gp \n"
"	addu $gp, $gp, $t0 \n"
"	jalrc $25 \n"
".set pop \n"
);
