__asm__(
".set push\n"
".set noreorder\n"
".text \n"
".global _" START "\n"
".global " START "\n"
".type   _" START ", @function\n"
".type   " START ", @function\n"
"_" START ":\n"
"" START ":\n"
"	move $fp, $zero \n"
"	.align 2 \n"
"	balc32 1f \n"
"	.gpword . \n"
"	.gpword " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
"	.gpword _DYNAMIC \n"
"1:	lw $t0, 0($ra) \n"
"	subu $t0, $ra, $t0 \n"
"	move $a0, $sp \n"
"	lw $a1, 8($ra) \n"
"	addu $a1, $a1, $t0 \n"
"	lw $t9, 4($ra) \n"
"	addu $t9, $t9, $t0 \n"
"	and $sp, $sp, -16 \n"
"	subu $sp, $sp, 16 \n"
"	la $gp, _gp \n"
"	addu $gp, $gp, $t0 \n"
"	jalrc $t9 \n"
".set pop \n"
);
